### ISSUE TITLE
Contact professors about advertising the kick-off

### ISSUE THREAD

**Issue by rosalogia** [openutd/openutd.github.io#1]
We'd like to ask various CS professors if they wouldn't mind mentioning our upcoming kick-off to their classes. While we can email them, it would be nice if some members could ask their professors in person if they'd do this for us. We should make a list of professors we want to reach out to and contact them 1-2 weeks prior to the event.

**Comment by graysoncroom** [comment]
I'll be giving a short introduction to OpenUTD during Dr. Becker's Digital Logic lecture today and telling ppl to come out to our event this coming Monday.
